<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
    <PackageReference Include="QuestPDF" Version="2024.7.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Amaretto.Infraestructure\Amaretto.Infraestructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="DTOs\ComboDTO.cs" />
  </ItemGroup>

</Project>
