<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />
    <PackageReference Include="X.PagedList.Mvc.Core" Version="9.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Amaretto.Application\Amaretto.Application.csproj" />
    <ProjectReference Include="..\Amaretto.Infraestructure\Amaretto.Infraestructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Logs\" />
    <Folder Include="wwwroot\images\productos\" />
  </ItemGroup>

</Project>
